Fixed: removed stow as it wouldn't work

diff --git a/install/ubuntu-setup b/install/ubuntu-setup
--- a/install/ubuntu-setup
+++ b/install/ubuntu-setup
@@ -1,11 +1,8 @@
 #!/bin/bash
 
 DOTFILES=$HOME/.dotfiles
-cd "$DOTFILES"
 
-# Define the list of files to stow
 FILES=(
-    "git/.gitconfig .gitconfig"
     "zsh/.zshrc .zshrc"
     "zsh/.zprofile .oh-my-zsh/custom/.zprofile"
     "zsh/aliases.zsh .oh-my-zsh/custom/aliases.zsh"
@@ -14,19 +11,17 @@ FILES=(
     "i3/config .config/i3/config"
 )
 
-# Check if stow is installed
-if ! command -v stow &> /dev/null; then
-    echo "Stow is not installed. Please install it before running this script."
-    exit 1
-fi
-
-# Loop through the files and stow them
+# Loop through the files and symlink them
 for file in "${FILES[@]}"; do
     source_file="$DOTFILES/${file%% *}"
     target_file="$HOME/${file##* }"
-    echo "Stowing $source_file to $target_file"
-    if ! stow --adopt -v -t "$HOME" --target="$target_file" "$source_file"; then
-        echo "Stowing failed for $source_file. Check the stow command and try again."
+    echo "Symlinking $source_file to $target_file"
+
+    # Create symbolic links
+    ln -sf "$source_file" "$target_file"
+
+    if [ $? -ne 0 ]; then
+        echo "Symlinking failed for $source_file. Check the ln command and try again."
         exit 1
     fi
 done
@@ -44,4 +39,5 @@ nvim +PlugInstall +qall
 ~/.tmux/plugins/tpm/bin/install_plugins
 
 echo "Dotfiles setup completed."
+
 
